version: '2'
services:
  core:
    container_name: mob_core
    build:
      context: .
      dockerfile: Dockerfile.elixir
    ports:
      - "4000:4000"
    volumes:
      - ./ApiCore:/app
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    links:
      - maria:maria
      - ai:ai
    restart: always
  ai:
    container_name: mob_ai
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "8880:8888"
      - "4141:5000"
    volumes:
      - ./AI:/app
    links:
      - maria:maria
    restart: always
  maria:
    container_name: mob_maria
    image: mariadb:10.3
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xourixos
      - MYSQL_DATABASE=where2go
      - MYSQL_USER=fsa
      - MYSQL_PASSWORD=xourixos
    restart: always