FROM tensorflow/tensorflow:1.2.0

RUN apt-get update && \
    apt-get -y install python-tk

RUN pip install flask

RUN pip install virtualenv
RUN virtualenv flask
RUN flask/bin/pip install flask

EXPOSE 5000

CMD ["python", "/app/app.py"]